# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='whats_app_group_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
