# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_live_whats_app_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='manager_contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='manager_name',
            field=models.CharField(default='Shibu Rbz', max_length=120),
        ),
        migrations.AddField(
            model_name='live',
            name='owner_contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='owner_name',
            field=models.CharField(default='Abishon RT', max_length=120),
        ),
    ]
