# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20191018_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='name',
            field=models.CharField(default='links', max_length=120),
        ),
    ]
