# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20191018_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='manager_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='live',
            name='owner_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
