# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_auto_20191023_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='registration',
            field=models.BooleanField(default=False),
        ),
    ]
