# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_live_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='youtube_live',
            field=models.BooleanField(default=False),
        ),
    ]
