# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_live_youtube_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='display_messages',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
