# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_live_display_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live',
            old_name='display_messages',
            new_name='display_messages_1',
        ),
        migrations.AddField(
            model_name='live',
            name='display_messages_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='display_messages_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
