# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
