# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import recent_match.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=120)),
                ('match_image', models.ImageField(blank=True, null=True, upload_to=recent_match.models.upload_image_path)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
