# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import recent_match.models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentmatch',
            name='match_image',
            field=models.ImageField(upload_to=recent_match.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='recentmatch',
            name='match_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
