# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120, unique=True)),
                ('player_1', models.CharField(max_length=120, unique=True)),
                ('player_1_pubg_id', models.CharField(max_length=120, unique=True)),
                ('player_2', models.CharField(max_length=120, unique=True)),
                ('player_2_pubg_id', models.CharField(max_length=120, unique=True)),
                ('player_3', models.CharField(max_length=120, unique=True)),
                ('player_3_pubg_id', models.CharField(max_length=120, unique=True)),
                ('player_4', models.CharField(max_length=120, unique=True)),
                ('player_4_pubg_id', models.CharField(max_length=120, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
