# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='final_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='match_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='semi_final_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='player_1_pubg_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='player_2_pubg_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='player_3_pubg_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='player_4_pubg_id',
            field=models.IntegerField(unique=True),
        ),
    ]
