# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191023_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
