# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_registration_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
